config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]
  namespace :api, defaults: { format: :json } do
    resources :followings
    resources :teams
    resources :blogs, only: [:new, :create, :show] do
      post "follow", to: "blogs#follow"
      delete "follow", to: "blogs#unfollow"
    end
    resources :posts, only: [:new, :create, :show, :destroy]
  end
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id          :integer          not null, primary key
#  author_id   :integer          not null
#  team_tag_id :integer          not null
#  title       :string(255)      not null
#  created_at  :datetime
#  updated_at  :datetime
#

class Blog < ActiveRecord::Base
  validates :author_id, :team_tag_id, :title, presence: true

  belongs_to :author, class_name: 'User'
  belongs_to :team, foreign_key: :team_tag_id
  has_one :league, through: :team
  has_many :posts
  has_many :followings
  has_many :followers, through: :followings, source: :user

  def is_owner?(user)
    user.id == self.author_id
  end

  def followed_by?(user)
    followers.include?(user)
  end
end

app/models/following.rb
# == Schema Information
#
# Table name: followings
#
#  id         :integer          not null, primary key
#  blog_id    :integer          not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Following < ActiveRecord::Base
  validates :user_id, :blog_id, presence: true
  validates :user_id, uniqueness: { scope: :blog_id }
  belongs_to :blog
  belongs_to :user
end

app/models/league.rb
# == Schema Information
#
# Table name: leagues
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class League < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :teams
  has_many :blogs, through: :teams
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  blog_id    :integer          not null
#  title      :string(255)      not null
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :blog_id, :title, presence: true

  belongs_to :blog
  has_one :team, through: :blog

  def is_owner?(user)
    user.id == self.blog.author_id
  end
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  league_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Team < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :league_id, presence: true

  belongs_to :league
  has_many :blogs, foreign_key: :team_tag_id
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :blogs, foreign_key: :author_id
  has_many :blogged_teams, through: :blogs, source: :team
  has_many :followings
  has_many :followed_blogs, through: :followings, source: :blog

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end


  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
  end
end

app/controllers/api/blogs_controller.rb
class Api::BlogsController < ApplicationController
  def new
    @blog = Blog.new
    @teams = Team.all
    render :new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.author_id = current_user.id

    if @blog.save
      render json: @blog
    else
      flash.now[:errors] = @blog.errors.full_messages
      render :new
    end
  end

  def show
    @blog = Blog.includes(:author, :followers, :posts).find(params[:id])
    render :show
  end

  private

    def blog_params
      params.require(:blog).permit(:title, :team_tag_id)
    end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def new

  end

  def create
    @post = Post.new(post_params)
    # @post.blog_id = params[:id]

    if @post.save
      render json: @post
    else
      render json: @post.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    
  end
  private

    def post_params
      params.require(:post).permit(:title, :body, :blog_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?

  def log_in!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def redirect_signed_in_users
    # redirect_to cats_url if current_user
  end

  def redirect_unsigned_in_users
    # redirect_to cats_url unless current_user
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def new
    @blog = Blog.new
    @teams = Team.all
    render :new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.author_id = current_user.id

    if @blog.save
      redirect_to blog_url(@blog)
    else
      flash.now[:errors] = @blog.errors.full_messages
      render :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
    render :show
  end

  private

    def blog_params
      params.require(:blog).permit(:title, :team_tag_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :redirect_signed_in_users, only: :new

  def new
    @user = User.new
    render :new
  end

  def create
    username = params[:user][:username]
    password = params[:user][:password]
    user = User.find_by_credentials(username, password)

    if user.nil?
      @user = User.new(user_params)
      flash.now[:errors] = ["Invalid login"]
      render :new
    else
      log_in!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  private

    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :redirect_signed_in_users, only: :new

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @teams = Team.all
    render :show
  end

  def index
    @users = User.all
    render :index
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="/" class="navbar-brand">Spumblr: the sports Tumblr!</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">

      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle"
           data-toggle="dropdown"
           href="javascript:void(0)"
           role="button"
           aria-expanded="false">
        MLB
        </a>
        <ul class="dropdown-menu" role="menu">
          <% Team.all.each do |team| %>
            <% if team.league_id == 1 %>
              <li><a class="team-<%= team.id %>" href="/#teams/<%= team.id %>"><%= team.name %> <span class="badge"><%= team.blogs.length %></span></a></li>
            <% end %>
          <% end %>
        </ul>
      </li>

      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle"
           data-toggle="dropdown"
           href="javascript:void(0)"
           role="button"
           aria-expanded="false">
        NFL
        </a>
        <ul class="dropdown-menu" role="menu">
          <% Team.all.each do |team| %>
            <% if team.league_id == 2 %>
              <li><a class="team-<%= team.id %>" href="/#teams/<%= team.id %>"><%= team.name %> <span class="badge"><%= team.blogs.length %></span></a></li>
            <% end %>
          <% end %>
        </ul>
      </li>

      <li role="presentation" class="dropdown">
        <a class="dropdown-toggle"
           data-toggle="dropdown"
           href="javascript:void(0)"
           role="button"
           aria-expanded="false">
        NBA
        </a>
        <ul class="dropdown-menu" role="menu">
          <% Team.all.each do |team| %>
            <% if team.league_id == 3 %>
              <li><a class="team-<%= team.id %>" href="/#teams/<%= team.id %>"><%= team.name %> <span class="badge"><%= team.blogs.length %></span></a></li>
            <% end %>
          <% end %>
        </ul>
      </li>

      <li><%= link_to "All users", users_url %></li>

      <% if signed_in? %>
        <li><%= link_to "#{current_user.username}", user_url(current_user) %></li>
        <li><%= button_to "Sign out", session_url, method: :delete, class: "btn btn-primary navbar-btn" %></li>
      <% else %>
        <li><%= link_to "Log in", new_session_url %></li>
        <li><%= link_to "Sign up", new_user_url %></li>
      <% end %>
    </ul>
  </div>
</div>
</nav>
<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spumblr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/header" %>

<%= yield %>

<script>
  window.SpumblrAppCU = function() {
      return <%= current_user.id if current_user %>;
  }
</script>
</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_logout.html.erb
<form action="/session" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <input type="submit" value="Logout!">
</form>